# Generated by Django 3.1.4 on 2020-12-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
