# Generated by Django 5.0 on 2023-12-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='year',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='year',
        ),
    ]
