# Generated by Django 5.0 on 2023-12-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_year_remove_topic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.year'),
        ),
    ]
